In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [12]:
a=np.asarray(l)

In [8]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [9]:
b=np.matrix(l)

In [10]:
b

matrix([[1, 2, 3, 4]])

In [11]:
type(b)

numpy.matrix

In [13]:
c=a

In [14]:
c

array([1, 2, 3, 4])

In [15]:
c[0]=14

In [16]:
c

array([14,  2,  3,  4])

In [17]:
d=np.copy(a)

In [18]:
d

array([14,  2,  3,  4])

In [19]:
a

array([14,  2,  3,  4])

In [20]:
a[1]=58

In [21]:
d

array([14,  2,  3,  4])

In [22]:
a

array([14, 58,  3,  4])

In [27]:
# 
np.fromfunction(lambda x,y: x==y,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i,j : (i*j) ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [53]:
itr=(i**2 for i in range(0,5))

In [54]:
np.fromiter(itr,float)

array([ 0.,  1.,  4.,  9., 16.])

In [56]:
np.fromstring('234,234',sep=',')

array([234., 234.])

In [57]:
# numpy datatypes

In [59]:
l=[2,3,4,5,6]

In [60]:
ar=np.array(l)

In [61]:
ar

array([2, 3, 4, 5, 6])

In [62]:
ar.ndim

1

In [65]:
arr2=np.array([[1,2,3,4],[3,4,5,6]])

In [67]:
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [68]:
arr2.size

8

In [69]:
arr2.shape

(2, 4)

In [70]:
arr2.ndim

2

In [71]:
arr2.dtype

dtype('int32')

In [74]:
ar22=np.array([(1,2,3,4,),(22,33,44,55)])

In [75]:
ar22

array([[ 1,  2,  3,  4],
       [22, 33, 44, 55]])

In [76]:
ar22.dtype

dtype('int32')

In [80]:
np.arange(2.3,6.5,0.1)

array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4])

In [81]:
list(np.arange(2.3,6.5,0.1))

[2.3,
 2.4,
 2.5,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1000000000000005,
 3.2000000000000006,
 3.3000000000000007,
 3.400000000000001,
 3.500000000000001,
 3.600000000000001,
 3.700000000000001,
 3.800000000000001,
 3.9000000000000012,
 4.000000000000002,
 4.100000000000001,
 4.200000000000001,
 4.300000000000002,
 4.400000000000002,
 4.500000000000002,
 4.600000000000001,
 4.700000000000002,
 4.8000000000000025,
 4.900000000000002,
 5.000000000000002,
 5.100000000000002,
 5.200000000000003,
 5.3000000000000025,
 5.400000000000002,
 5.500000000000003,
 5.600000000000003,
 5.700000000000003,
 5.8000000000000025,
 5.900000000000003,
 6.0000000000000036,
 6.100000000000003,
 6.200000000000003,
 6.300000000000003,
 6.400000000000003]

In [82]:
[np.arange(2.3,6.5,0.1)]

[array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
        3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
        4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
        6.2, 6.3, 6.4])]

In [83]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [88]:
np.ones(4)

array([1., 1., 1., 1.])

In [89]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
on=np.ones((2,2,3))

In [92]:
on+5

array([[[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]]])

In [93]:
on*2

array([[[2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.]]])

In [95]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [96]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [100]:
np.logspace(2,5,12,base=3)

array([  9.        ,  12.14413225,  16.3866609 ,  22.11130856,
        29.83585059,  40.25894615,  54.32332958,  73.30107762,
        98.9086645 , 133.46221136, 180.08697166, 243.        ])

In [107]:
rnd=np.random.randn(3,4)

In [108]:
import pandas as pd

In [109]:
pd.DataFrame(rnd)

0         1         2         3
0  0.244212 -1.630741  1.087277 -0.308453
1  0.108853 -1.093954 -0.262800  0.254316
2 -1.238543 -1.324939 -1.154357 -0.104408

In [112]:
arr=np.random.rand(3,4)

In [116]:
arr

array([[0.46844516, 0.92097673, 0.9621337 , 0.71482198],
       [0.42409454, 0.10090397, 0.23485611, 0.98727876],
       [0.37422867, 0.11402946, 0.98911868, 0.15702256]])

In [114]:
np.random.randint(1,101,(6,4))

array([[31, 25,  3, 78],
       [39, 58,  8, 78],
       [73, 46, 69, 66],
       [75, 91, 67,  6],
       [42, 23, 68, 70],
       [72, 41, 46, 15]])

In [115]:
arr.reshape(4,3)

array([[0.46844516, 0.92097673, 0.9621337 ],
       [0.71482198, 0.42409454, 0.10090397],
       [0.23485611, 0.98727876, 0.37422867],
       [0.11402946, 0.98911868, 0.15702256]])

In [118]:
arr1=arr.reshape(4,-2)

In [119]:
arr1

array([[0.46844516, 0.92097673, 0.9621337 ],
       [0.71482198, 0.42409454, 0.10090397],
       [0.23485611, 0.98727876, 0.37422867],
       [0.11402946, 0.98911868, 0.15702256]])

In [122]:
arr1[1][1]

0.4240945393951224

In [123]:
arr1[2][2]

0.37422867085034883

In [127]:
arr1[1:3,1]

array([0.42409454, 0.98727876])

In [129]:
arr=np.random.randint(1,100,(5,5))

In [130]:
arr

array([[60, 70, 54, 93, 79],
       [33, 90, 80, 18, 95],
       [55, 96, 12, 81, 36],
       [56, 50, 86, 36, 96],
       [55, 55, 97, 44,  9]])

In [132]:
arr[arr>60]

array([70, 93, 79, 90, 80, 95, 96, 81, 86, 96, 97])

In [136]:
arr[2:4,1:3]

array([[96, 12],
       [50, 86]])

In [137]:
arr[0][0]=12345

In [138]:
arr

array([[12345,    70,    54,    93,    79],
       [   33,    90,    80,    18,    95],
       [   55,    96,    12,    81,    36],
       [   56,    50,    86,    36,    96],
       [   55,    55,    97,    44,     9]])

In [139]:
arr1=np.random.randint(1,3,(3,3))

In [140]:
arr2=np.random.randint(1,3,(3,3))

In [141]:
arr1

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [142]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [143]:
arr1+arr2

array([[4, 4, 3],
       [3, 3, 3],
       [2, 2, 3]])

In [144]:
arr1*arr2

array([[4, 4, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [145]:
arr1-arr2

array([[ 0,  0, -1],
       [-1, -1, -1],
       [ 0,  0,  1]])

In [146]:
arr1/arr2

array([[1. , 1. , 0.5],
       [0.5, 0.5, 0.5],
       [1. , 1. , 2. ]])

In [147]:
#matrix multiplication

In [149]:
arr1@arr2

array([[9, 9, 9],
       [5, 5, 5],
       [6, 6, 6]])

In [151]:
row=np.array([1,2,3,4])

In [155]:
arr=np.zeros((4,4))

In [156]:
row

array([1, 2, 3, 4])

In [157]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [158]:
col=np.array([[1,2,3,4]])

In [159]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [160]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [161]:
amr=np.random.randint(1,4,(3,4))

In [164]:
np.sqrt(amr)

array([[1.41421356, 1.73205081, 1.73205081, 1.41421356],
       [1.73205081, 1.        , 1.73205081, 1.        ],
       [1.        , 1.41421356, 1.41421356, 1.73205081]])

In [165]:
np.log10(amr)

array([[0.30103   , 0.47712125, 0.47712125, 0.30103   ],
       [0.47712125, 0.        , 0.47712125, 0.        ],
       [0.        , 0.30103   , 0.30103   , 0.47712125]])

In [166]:
# array manipulation:


In [167]:
import numpy as np

In [168]:
arr=np.random.randint(1,10,(3,4))

In [169]:
arr

array([[3, 5, 5, 1],
       [6, 9, 2, 1],
       [9, 7, 8, 7]])

In [170]:
arr.reshape(6,2)

array([[3, 5],
       [5, 1],
       [6, 9],
       [2, 1],
       [9, 7],
       [8, 7]])

In [171]:
arr.reshape(2,-1)

array([[3, 5, 5, 1, 6, 9],
       [2, 1, 9, 7, 8, 7]])

In [172]:
arr.T

array([[3, 6, 9],
       [5, 9, 7],
       [5, 2, 8],
       [1, 1, 7]])

In [173]:
arr.flatten()

array([3, 5, 5, 1, 6, 9, 2, 1, 9, 7, 8, 7])

In [174]:
arr1=np.array([1,2,3,4,5])

In [175]:
arr1.ndim

1

In [176]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [178]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [179]:
np.squeeze(arr)

array([[3, 5, 5, 1],
       [6, 9, 2, 1],
       [9, 7, 8, 7]])

In [180]:
data=np.array([[1],[2],[3]])

In [181]:
data

array([[1],
       [2],
       [3]])

In [182]:
np.squeeze(data)

array([1, 2, 3])

In [184]:
arr1

array([1, 2, 3, 4, 5])

In [183]:
# two place shift
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [185]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [186]:
# Binary operation

In [188]:
arr1=np.random.randint(1,10,(3,4))

In [189]:
arr2=np.random.randint(1,10,(3,4))

In [190]:
arr1

array([[4, 1, 1, 1],
       [3, 5, 6, 2],
       [6, 2, 3, 2]])

In [191]:
arr2

array([[8, 8, 1, 9],
       [3, 7, 6, 4],
       [2, 5, 2, 2]])

In [192]:
arr1+arr2

array([[12,  9,  2, 10],
       [ 6, 12, 12,  6],
       [ 8,  7,  5,  4]])

In [193]:
arr1*arr2

array([[32,  8,  1,  9],
       [ 9, 35, 36,  8],
       [12, 10,  6,  4]])

In [194]:
arr1/arr2

array([[0.5       , 0.125     , 1.        , 0.11111111],
       [1.        , 0.71428571, 1.        , 0.5       ],
       [3.        , 0.4       , 1.5       , 1.        ]])

In [195]:
arr1-arr2

array([[-4, -7,  0, -8],
       [ 0, -2,  0, -2],
       [ 4, -3,  1,  0]])

In [196]:
arr1%arr2

array([[4, 1, 0, 1],
       [0, 5, 0, 2],
       [0, 2, 1, 0]], dtype=int32)

In [197]:
arr1**arr2

array([[65536,     1,     1,     1],
       [   27, 78125, 46656,    16],
       [   36,    32,     9,     4]], dtype=int32)

In [198]:
arr1 & arr2

array([[0, 0, 1, 1],
       [3, 5, 6, 0],
       [2, 0, 2, 2]], dtype=int32)

In [199]:
~arr1

array([[-5, -2, -2, -2],
       [-4, -6, -7, -3],
       [-7, -3, -4, -3]], dtype=int32)

In [200]:
arr1 | arr2

array([[12,  9,  1,  9],
       [ 3,  7,  6,  6],
       [ 6,  7,  3,  2]], dtype=int32)

In [201]:
arr1>arr2

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [202]:
arr1<arr2

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [204]:
# string function:

arr=np.array(['sudh','kumar'])

In [205]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [206]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [207]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [208]:
# mathematical function

In [210]:
np.sin(arr1)

array([[-0.7568025 ,  0.84147098,  0.84147098,  0.84147098],
       [ 0.14112001, -0.95892427, -0.2794155 ,  0.90929743],
       [-0.2794155 ,  0.90929743,  0.14112001,  0.90929743]])

In [211]:
np.cos(arr1)

array([[-0.65364362,  0.54030231,  0.54030231,  0.54030231],
       [-0.9899925 ,  0.28366219,  0.96017029, -0.41614684],
       [ 0.96017029, -0.41614684, -0.9899925 , -0.41614684]])

In [212]:
np.tan(arr1)

array([[ 1.15782128,  1.55740772,  1.55740772,  1.55740772],
       [-0.14254654, -3.38051501, -0.29100619, -2.18503986],
       [-0.29100619, -2.18503986, -0.14254654, -2.18503986]])

In [213]:
np.tanh(arr1)

array([[0.9993293 , 0.76159416, 0.76159416, 0.76159416],
       [0.99505475, 0.9999092 , 0.99998771, 0.96402758],
       [0.99998771, 0.96402758, 0.99505475, 0.96402758]])

In [214]:
np.exp(arr1)

array([[ 54.59815003,   2.71828183,   2.71828183,   2.71828183],
       [ 20.08553692, 148.4131591 , 403.42879349,   7.3890561 ],
       [403.42879349,   7.3890561 ,  20.08553692,   7.3890561 ]])

In [215]:
np.sqrt(arr1)

array([[2.        , 1.        , 1.        , 1.        ],
       [1.73205081, 2.23606798, 2.44948974, 1.41421356],
       [2.44948974, 1.41421356, 1.73205081, 1.41421356]])

In [216]:
np.power(arr1,2)

array([[16,  1,  1,  1],
       [ 9, 25, 36,  4],
       [36,  4,  9,  4]], dtype=int32)

In [217]:
np.mean(arr1)

3.0

In [218]:
np.std(arr1)

1.7795130420052185

In [219]:
np.max(arr1)

6

In [220]:
# sorting ,searching and counting:

In [222]:
arr=np.array([1,3,13,243,45,5,345,54,7,5])

In [223]:
arr

array([  1,   3,  13, 243,  45,   5, 345,  54,   7,   5])

In [224]:
np.sort(arr)

array([  1,   3,   5,   5,   7,  13,  45,  54, 243, 345])

In [225]:
np.searchsorted(arr,13)

10

In [226]:
arr1=np.array([0,234,434,0,0,0,0,0])

In [227]:
arr1

array([  0, 234, 434,   0,   0,   0,   0,   0])

In [228]:
np.count_nonzero(arr1)

2

In [230]:
np.where(arr1>6)

(array([1, 2], dtype=int64),)

In [231]:
np.extract(arr1>6,arr1)

array([234, 434])

In [232]:
arr1.byteswap()

array([          0,  -369098752, -1308557312,           0,           0,
                 0,           0,           0])